1. Deklarasi Matriks

In [1]:
matriks =[[1,2,3], [4,5,6]]
print(matriks)

[[1, 2, 3], [4, 5, 6]]


In [2]:
import numpy as np

In [3]:
matriks = np.array([[1,2,3], [4,5,6]])
print(matriks)

[[1 2 3]
 [4 5 6]]


In [5]:
# scalar
scalar = np.array(5)
print(scalar)

# vektor baris
row_vector = np.array([1,2,3])
print(row_vector)

# vektor kolom
col_vector = np.array([[1], [2], [3]])
print(col_vector)

5
[1 2 3]
[[1]
 [2]
 [3]]


In [7]:
#matriks 2d
matriks_2d = np.array([[1,2,3], [4,5,6]])
print(matriks_2d)

#matriks 3d
matriks_3d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("matriks 3x3")

[[1 2 3]
 [4 5 6]]
matriks 3x3


In [13]:
zeros_matrikx = np.zeros((3,3))
print("matriks nol (3x3):\n", zeros_matrikx)
#klo kek diatas entar 0 isinya

#buat isi 0 jadi 5
zeros_matrikx[0,0] = 5
print(zeros_matrikx[0,0])

ones_matrikx = np.ones((2,4))
print("matriks satu (2x4):\n", ones_matrikx)

identity_matrikx = np.eye(4)
print("matriks identitas (4x4):\n", identity_matrikx)

random_matrix = np.random.rand(3,3)
print("matriks acak (3x3):\n", random_matrix)

random_int_matrix = np.random.randint(1, 11, size=(3,3))
print("matriks acak integer (3x3):\n", random_int_matrix)


matriks nol (3x3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
5.0
matriks satu (2x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
matriks identitas (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
matriks acak (3x3):
 [[0.53814862 0.20595394 0.34157365]
 [0.38033798 0.17204916 0.89796152]
 [0.73960038 0.88875678 0.30893401]]
matriks acak integer (3x3):
 [[ 2  2  9]
 [ 8 10  8]
 [ 3  6  1]]


2.akses elemen matriks

In [15]:
A= np.array([[1,2,3], [4,5,6], [7,8,9]])

print("eleman baris 1, kolom ke 2:", A[0,1])
print("eleman baris 2, kolom ke 1:", A[1,0])

print("baris ke 2:", A[1,:])
print("kolom ke 3:", A[:,2]) 

eleman baris 1, kolom ke 2: 2
eleman baris 2, kolom ke 1: 4
baris ke 2: [4 5 6]
kolom ke 3: [3 6 9]


3.operasi matriks

In [ ]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

#perkalian
c = A * B
print("perkalian antar elemen A dan B:\n", c)

c = A + B
c = A-B
c = A/B 
c = A**B #pangkat

perkalian elemen A dan B:
 [[ 5 12]
 [21 32]]


In [ ]:
A= np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

c= np.dot(A, B)
print("perkalian matriks A dan B:\n", c)

inv_A = np.linalg.inv(A) #membagi elemen ke 2
print("invers matriks A:\n", inv_A)
A_T = A.T
print("transpose matriks A:\n", A_T)

perkalian matriks A dan B:
 [[19 22]
 [43 50]]
invers matriks A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [20]:
det_A = np.linalg.det(A)
print("determinan matriks A:", det_A)

elgevalues, elgevectors = np.linalg.eig(A)
print("nilai eign:", elgevalues)
print("vektor eign:\n", elgevectors)

rank_A = np.linalg.matrix_rank(A)
print("rank matriks A:", rank_A)

determinan matriks A: -2.0000000000000004
nilai eign: [-0.37228132  5.37228132]
vektor eign:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
rank matriks A: 2


In [ ]:
#matriks koefesien
A= np.array([[1,2], [12,5]])

#vektors konstanta
B = np.array([32, 7])

A_inv = np.linalg.inv(A)

x = np.dot(A_inv, B)
print("solusi x:\n", x)
#BEDA KENAPA?//

solusi x:
 [-7.68421053 19.84210526]


In [ ]:
X = np.linalg.solve(A, B)
print("solusi x dengan np.linalg.solve:\n", X)

solusi x dengan np.linalg.solve:
 [-7.68421053 19.84210526]


4,penggabungan matriks

In [25]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

#gabung horisontal
H= np.hstack((A, B))
print("matriks hasil horizontal stack:\n", H)

matriks hasil horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]


penggabungan vertikal

In [26]:
v= np.vstack((A, B))
print("matriks hasil vertical stack:\n", v)

matriks hasil vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


pembentukan ulang matriks

In [27]:
#mengubah dimensi matriks
A = np.array([1,2,3,4,5,6])

reshaped_A = A.reshape((2,3))
print("matriks A yang diubah dimensinya (2x3):\n", reshaped_A)


matriks A yang diubah dimensinya (2x3):
 [[1 2 3]
 [4 5 6]]


In [ ]:
#meratakan dimensi matriks
B = np.array([[1,2,3], [4,5,6]])

flattened_B = B.flatten()
print("matriks B yang diratakan:\n", flattened_B)